name = "BenchmarkCI"
uuid = "20533458-34a3-403d-a444-e18f38190b5b"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.3"

[deps]
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
CpuId = "0.2"
JSON = "0.21"
PkgBenchmark = "0.2.8"
Setfield = "0.1, 0.2, 0.3, 0.4, 0.5, 0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
